#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

$customConfig = require __DIR__ . '/env_bootstrap.php';

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$customConfig = require __DIR__ . '/yii_bootstrap.php';
$config = \yii\helpers\ArrayHelper::merge(require __DIR__ . '/config/console.php', $customConfig);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
